os:
  - osx
  language: node_js
  node_js:
    - "10"
  cache: yarn
  - linux
  language: node_js
  node_js:
    - "10"
  cache: yarn

matrix:
  fast_finish: true

jobs:
  include:
    - stage: test
      script: yarn build && yarn test
